spring:
  application:
    name: currency-gif-service
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

oxr:
  url: "https://openexchangerates.org/api/"
  app_id: "9dd5e0127b1d4aeca5511609c7b30b22"
  current_currency: "EUR" #Любая валюта
giphy:
  url: "https://api.giphy.com/v1/gifs"
  api_key: "1PqxFoSDf8qvb6z4i71TqXuaGKc0QBWy"