spring:
  application:
    name: currency-gif-service
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

oxr:
  url: "https://openexchangerates.org/api/"
  app_id: "YOUR_OPENEXCHANGERATES_APP_ID_HERE"
  current_currency: "EUR" #Любая валюта
giphy:
  url: "https://api.giphy.com/v1/gifs"
  api_key: "YOUR_GIPHY_API_KEY_HERE"